### ISSUE TITLE
[UI] Clicking on list category buttons should refresh lists

### ISSUE THREAD

**Issue by lumjjb** [lumjjb/tornjak#10]
Clicking on agents/entries should refresh the entries displayed.. 

Navbar is implemented in:
https://github.com/lumjjb/tornjak/blob/main/tornjak-frontend/src/components/navbar.component.js

List is updated in:
https://github.com/lumjjb/tornjak/blob/main/tornjak-frontend/src/components/entry-list.component.js#L45

**Comment by mamy-CS** [comment]
https://github.com/lumjjb/tornjak/pull/18
